version: '2'

services:
  drupal:
    image: drupal
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/modules
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: drupal
      POSTGRES_USER: user

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites: